---
title: "Graph Challenge 3"
author: "Your Name"
date: "`r Sys.Date()`"
format: 
  docx:
    number-sections: true
    number-depth: 3
    fig-dpi: 500
    fig-align: center
    fig-height: 4
    fig-width: 6
execute: 
  echo: true
  warning: false
  message: false
---

**Instructions**: Read in the dataset located at this url:

https://raw.githubusercontent.com/milesdwilliams15/dpr-101-project-files/refs/heads/main/_data/florida.csv

The data provides county-level detail for the state of Florida on candidate vote totals and vote shares in the 1996 and 2000 U.S. presidential elections. Some columns are a count of the total ballots cast for a specific candidate in each county. Others are shares of a candidate's votes out of all votes for president in a given county. If you remember back when we read "The Butterfly Did It," the 2000 election is the one where the butterfly ballot design in Palm Beach County, Florida resulted in thousands of erroneous votes cast for Pat Buchanan.

Use this data to create *two* data visualizations. Both should be scatter plots that include lines of best fit. Both should also highlight Palm Beach County using different colored data points and a legend. The only thing that should be different between the data visualizations is that one will show Buchanan's vote total in 2000 (Buchanan00) predicted by Ross Perot's (Perot96) in 1996, and the other will show Buchanan's vote share in 2000 (prop_Buchanan00) predicted by Ross Perot's in 1996 (Perot96). After you've made both figures, in a paragraph at the end, answer the following questions: 

1. Does looking at vote shares lead to a different conclusion about Palm Beach County's weirdness? 

2. What might explain why the results look different?

3. Which way is the right way to examine the data: shares or totals?