---
title: "Graph Challenge 5"
author: "Your Name Here"
date: "`r Sys.Date()`"
format: 
  docx:
    number-sections: true
    number-depth: 3
    fig-dpi: 500
    fig-align: center
    fig-height: 4
    fig-width: 6
execute: 
  echo: true
  warning: false
  message: false
---

For this graph challenge your mission is to create a plot showing the percentage of countries in the world involved in a conflict with any other country in the world from 1816 to 2014. You'll use the "peacesciencer" package to create your dataset. Below the figure, write a short summary that makes an assertion about what the data says (the finding) about country involvement in conflicts over time and explains how the plot supports your assertion.

The appearance of the plot is up to you. It could be a line plot, a column plot, or even a scatter plot (potentially with a smoothed regression line). Just make it look good and make smart choices.

The hardest part of this challenge isn't the data visualization itself. It's constructing the dataset you need to make the plot. But don't worry, I've broken the problem down into steps. If you follow them, you should have no trouble.

Here they are:

1. Create a dyad-year dataset and add conflict data to it (use `add_cow_mids()`).

2. Use a combination of `group_by()` and `summarize()` to make a dataset at the country-year level for country 1 with a column indicating the number of times a given country was in a MID with another country in the data.

3. Use `mutate()` to add a new column to the dataset that is a 1 in years that a country was involved in a MID and a 0 otherwise.

4. Group the data by year and summarize the number of countries involved in a MID.

5. Plot the results.



