---
title: "Main Assignment 2"
format: docx
---

Is war disappearing? This is the question we've been asking again and again in this unit of the class. It also is the question you'll try to find an answer to in this main assignment. But, there's going to be a twist.

As you already know, you can get different answers to this question based on how you choose to look at the data. But you might also get some different answers by looking at different datasets entirely. So let me introduce you to the new [Militarized Interstate Confrontations](https://internationalconflict.ua.edu/data-download/) (MIC) dataset hosted by the [International Conflict Data Project](https://internationalconflict.ua.edu/) at the University of Alabama.

If you read [the associated documentation](https://internationalconflict.ua.edu/wp-content/uploads/2023/07/MICcodebook.pdf), you'll see that the MIC dataset was created in response to deficiencies in the Correlates of War [Militarized Interstate Dispute](https://correlatesofwar.org/data-sets/mids/) (MID) dataset. After a lengthy and unproductive back-and-forth with the MID dataset folks, the political scientists Douglas Gibler and Steve Miller set out to create a new dataset that would both rival and surpass the MID dataset. As these researchers state in their documentation:

> Our data collection efforts began with the original Militarized Interstate Dispute (MID) dataset from the Correlates of War Project (CoWMID) (Jones, Bremer and Singer, 1996). We found an overwhelming number of errors in the original data and corrected those data, providing all of our suggested changes to the CoWMID Project dataset hosts. However, after more than nine years of communications with CoWMID and several exchanges in *International Studies Quarterly*, it is apparent that CoWMID admits their pre-2002 data is incredibly error-prone but that they have neither the resources nor inclination to fix those thousands of admitted errors. Therefore, we are introducing the Militarized Interstate Confrontation (MICs) data, which are based on proper use of MID coding rules and include numerous advancements in both information and presentation.

In short, these guys claim to have made the dataset that CoWMID always wanted to have, but failed to produce (either through lack of resources or will power).

That's a tall order, but the more interesting implication that comes from this new dataset is that it might offer a different answer to the question of whether war is disappearing. After all, the MIC dataset creators say they've fixed several thousand errors in CoWMID. That seems substantial.

**Your goal in this main assignment is to write up an analysis that compares the MID and MIC datasets to see if they provide similar or conflicting inferences about the occurrence of international conflict over the past two centuries.**

Your analysis will center around **two figures**. One will compare the count of conflicts over time, and the other will compare the conflict rate over time. Each figure will show the trend for the MID and MIC datasets in parallel, and both should showcase three skills that we learned this unit: (1) use of the `{geomtextpath}` package, (2) use of `{coolorrr}`, and (3) use of a custom plotting theme. You'll need to do some data wrangling to make each figure, too.

You have some choices about the variables you'll use to count up conflicts and to calculate rates, and you'll need to offer justifications for the choices you end up making. You might choose to count unique conflict instances, or you might choose to count the number of country pairs involved in conflicts. Also, you might choose to calculate the conflict rate per all country pairs, or only by politically relevant country pairs. In the latter case, you have two options for calculating political relevance. A variable called "prd1" is the classic measure of relevance which takes the value "1" if a country in a pair is a major power or if the countries are contiguous (sharing a border or separated by no more than 400 miles of water). Another variable called "prd2" is the [Braumoeller-Carson measure of relevance](https://journals.sagepub.com/doi/10.1177/0022002710393918) which is probabilistic rather than deterministic, meaning it takes a value between 0 and 1 where values closer to 1 mean that the chance that two countries could reach each other to fight is high.

You'll write up your findings in a report. You may use the main assignment Quarto template attached in Canvas. Below I've listed out an outline for how I expect this report to look. Each item is worth an equal share of your final grade.

## Preamble

-   Include a title for your submission.

-   Include your name.

## Introduction

-   Include a section header.

-   Should be one paragraph.

-   Use clear and plain writing with smooth transitions and no more than two typos or grammatical errors.

-   Clearly state your research question (must end with a question mark).

-   Explain why the question matters (context, relevance, importance).

## Data and Design

-   Include a section header.

-   Two paragraphs (no more or less).

-   Use clear and plain writing with smooth transitions and no more than two typos or grammatical errors.

-   Do not use bullet points or numbered lists.

-   Paragraph 1 – Describe the Data:

    -   State the unit of analysis (e.g., “yearly conflict data”).

    -   Indicate the sources of your data (MIC and MID).

    -   Provide a brief summary of key variables (e.g., number of uses of force between countries, number of politically relevant country pairs), and provide a justification for the ones you select.

    -   Do not refer to variables using the raw column names in the dataset.

-   Paragraph 2 – Describe Your Design/Approach:

    -   Explain how you plan to use or visualize the data.

    -   Do not refer to specific R functions or packages as you describe how you'll visualize the data.

# Analysis

-   Include a section header.

-   Two paragraphs (no more or less).

-   Use clear and plain writing with smooth transitions and no more than two typos or grammatical errors.

-   Do not use bullet points or numbered lists.

-   No raw R output, tables, or statistical model results may appear anywhere in the text.

-   Include 2 data visualizations in total (no more or less).

-   Both data visualizations must demonstrate use of `{geomtextpath}`, a custom color palette with `{coolorrr}`, and a custom plotting theme.

-   All data visualizations must have:

    -   A figure number and title (e.g., “Figure 1: The title...”).

    -   The title should follow the assertion–evidence format where the title states the finding from the data you want to highlight.

    -   No sub-figure numbering (e.g., do not use “Figure 1a” / “1b”).

    -   Clear labels without typos, no chart junk, and no data errors.

-   For each data visualization write a paragraph that:

    -   Comes *before* the data visualization.

    -   Starts with a clear assertion about what the data shows.

    -   Gives a brief summary of how to "read" the visualization so your readers can see how the data supports your assertion.

## Conclusion

-   Include a section header.

-   1-2 paragraphs.

-   Use clear and plain writing with smooth transitions and no more than two typos or grammatical errors.

-   Summarize your findings.

-   Go beyond summary and offer broader insights or claims about the implications of your findings.

## Code appendix

You should have all of the code used for the analysis appear at the end of your submission.

## Citations

-   If you reference something that isn't common knowledge, you should cite your source.

-   Use in-text hyperlinks for citations rather than a traditional works cited style.

\clearpage

## Accessing the data

For this analysis you'll need to start by creating a dyad-year dataset that you then populate with MID and MIC variables, along with information on political relevance. From there you'll need to do some data wrangling to get it ready for visualization. The code below will get you started with the dyad-year data. The rest is up to you.

```{r}
#| eval: false
library(tidyverse)
library(peacesciencer)
source("https://tinyurl.com/peacesciencerextras") 
  # creates add_icd_mics() and add_relevance()

create_dyadyears(
  directed = F,
  subset_years = 1816:2014
) |>
  add_cow_mids() |>
  add_icd_mics() |>
  add_relevance() -> dt
```
